### ISSUE TITLE
Аутентификация по паролю.

### ISSUE THREAD

**Issue by alexandrov2226** [skbkontur/extern-csharp-sdk#20]
Какое значение записать в параметр log в конструкторе OpenIdClient Create:
        public static OpenIdClient Create(RequestTimeouts requestTimeouts, IHttpClientConfiguration clientConfiguration, ILog log)
        {
            var http = new HttpRequestFactory(
                clientConfiguration,
                requestTimeouts,
                null,
                HandleOpenIdErrorResponse,
                null,
                Serializer,
                log
            );
            return new OpenIdClient(http);
        }

**Comment by RuslanGatin** [comment]
Можно воспользоваться одной из имплементаций интерфейса ILog https://vostok.gitbook.io/logging/implementations или оберткой для других библиотек логирования https://vostok.gitbook.io/logging/integrations

**Comment by alexandrov2226** [comment]
Есть пример аутентификации по паролю?

**Comment by RuslanGatin** [comment]
Есть тест https://github.com/skbkontur/extern-csharp-sdk/blob/master/src/Kontur.Extern.Api.Client.Auth.OpenId.End2EndTests/Client/OpenIdClient_Tests.cs#L28

**Comment by RuslanGatin** [comment]
output в тесте подставляет XUnit. Это примерно аналогично тому, чтобы передать new ConsoleLog() в OpenIdClient.Create в качестве лога

**Comment by alexandrov2226** [comment]
Что записать в messageBus и test при инициализации testOutputHelper?:
TestOutputHelper testOutputHelper = new TestOutputHelper();
testOutputHelper.Initialize(messageBus, test);

**Comment by RuslanGatin** [comment]
TestOutputHelper не нужно создавать, его создает XUnit

**Comment by alexandrov2226** [comment]
то есть инициализировать не надо?

**Comment by RuslanGatin** [comment]
Чтобы запустить тест - не надо. Если хотите в продакшн-коде создать OpenIdClient, то в OpenIdClient.Create передавайте не TestLog, а тот логгер, который вам больше подходит: одну из имплементаций ILog или адаптер к Serilog, log4net или Microsoft.Extensions.Logging

**Comment by alexandrov2226** [comment]
Тогда из за чего может быть ошибка: There is no currently active test

**Comment by RuslanGatin** [comment]
Наверно какой-то поток продолжает писать логи, когда тест уже завершился. В каком тесте такая ошибка возникает? Можете приложить стектрейс?

**Comment by alexandrov2226** [comment]
at Xunit.Sdk.TestOutputHelper.GuardInitialized() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\TestOutputHelper.cs:line 52
   at Xunit.Sdk.TestOutputHelper.QueueTestOutput(String output) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\TestOutputHelper.cs:line 62
   at Xunit.Sdk.TestOutputHelper.WriteLine(String message) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\TestOutputHelper.cs:line 111

**Comment by alexandrov2226** [comment]
Можно задать в программе параметры прокси-сервера?

**Comment by RuslanGatin** [comment]
Такой возможности нет
