### ISSUE TITLE
Расширенное логирование (trace-id) & Передача кастомных заголовков

### ISSUE THREAD

**Issue by mrleo1nid** [skbkontur/extern-csharp-sdk#63]
Можно ли как то получить/ либо записывать в лог traceId запросов при выполнении любых операций?

**Comment by mrleo1nid** [comment]
И второй вопрос можно  ли как то добавить дополнительные хедеры к запросам? Просто у нас будет прокси через которые будут пробрасываться все запросы

**Comment by DEFLIK** [comment]
Доброго дня!
В ветке https://github.com/skbkontur/extern-csharp-sdk/pull/65 добавили логирование trace-id (в мастер влили)
Сообщение с trace-id будет отдано в класс лога, передаваемый на этапе создания ExternBuilder

> И второй вопрос можно ли как то добавить дополнительные хедеры к запросам? Просто у нас будет прокси через которые будут пробрасываться все запросы

По поводу хедеров хочется подробнее понять. Правильно понимаю, что все запросы этого SDK (к хосту https://extern-api.testkontur.ru, например) будут проксироваться и для этого прокси хочется отдавать какие-то дополнительные свои хедеры? Будут ли эти хедеры потом переданы от прокси к нашему API или останутся только у него?

Сейчас такой возможности нет, но можем реализовать трансформацию запросов при необходимости

**Comment by mrleo1nid** [comment]
> Доброго дня! В ветке #65 добавили логирование trace-id (в мастер влили) Сообщение с trace-id будет отдано в класс лога, передаваемый на этапе создания ExternBuilder
> 
> > И второй вопрос можно ли как то добавить дополнительные хедеры к запросам? Просто у нас будет прокси через которые будут пробрасываться все запросы
> 
> По поводу хедеров хочется подробнее понять. Правильно понимаю, что все запросы этого SDK (к хосту https://extern-api.testkontur.ru, например) будут проксироваться и для этого прокси хочется отдавать какие-то дополнительные свои хедеры? Будут ли эти хедеры потом переданы от прокси к нашему API или останутся только у него?
> 
> Сейчас такой возможности нет, но можем посмотреть в сторону реализации трансформации запросов в нашем СДК при необходимости

Да, понимаете верно, хэдеры будут использоваться для аутентификации на прокси сервере, по передачи их дальше к апи я уточню но так понимаю что не будут

**Comment by DEFLIK** [comment]
Хорошо, тогда добавим трансформацию запросов вместе с этой веткой https://github.com/skbkontur/extern-csharp-sdk/pull/66. В целом проблемы в передаче избыточных заголовков к нашему АПИ нет, но как раз в случае секретов - лучше будет их скрывать перед формированием запроса от прокси к нашему АПИ

О том, как прописать кастомные заголовки опишу в этом треде после обновления)

**Comment by DEFLIK** [comment]
Влили изменения в мастер

Пример создания кастомного заголовка
```
var client = new ExternBuilder()
    .WithHttpConfiguration(
        new ExternalUrlHttpClientConfiguration(new Uri("https://extern-api.testkontur.ru"))
            .WithRequestTransform(r => r.WithHeader("TestHeaderName", "TestValueValue")),
        new ConsoleLog())
    .WithAuthenticator(new AuthSidAuthenticator("...", "..."))
    .Create();
```
